#!/bin/bash -e

installDir=$(noelle-config --prefix)

# Delete dead functions until a fixed point is reached
echo "NOELLE: DeadFunctions: Start" ;
cmdToExecute="noelle-load -noelle-rm-function $@"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: DeadFunctions: Exit" ;
