#!/bin/bash -e

installDir

# Run the privatizer until a fixed point is reached
cmdToExecute="noelle-fixedpoint $1 $1 \"noelle-parallel-load\" -load ${installDir}/lib/Privatizer.so -privatizer ${@:2}"
echo $cmdToExecute ;
eval $cmdToExecute ;
