#!/bin/bash -e

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

echo "NOELLE: SCCPrinter: Start" ;
cmdToExecute="noelle-load -load ${installDir}/lib/SCCPrinter.so -scc-printer -disable-output $@"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: SCCPrinter: Exit" ;
