#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

usage() {
  echo "USAGE: `basename $0` INPUT_BC [OPTIONS]..."
  echo
  echo "Tool for parallelizing one loop at a time and running the binary."
  echo
  echo "INPUT_BC        Input bitcode with parallel plan and API already linked."
  echo "                Generally this file is code_to_parallelize.bc"
  echo
  echo "Options:"
  echo "--timeout       Seconds after which the executable will be interruped"
  echo "                causing a non-zero return code."
  echo "                If not specified the binary will not be run."
  echo "--args          Arguments to the executable."
  echo "--help          Display this message."
}

showReturnCode() {
  prefix=$1
  retCode=$2
  if test $retCode -eq 0 ; then
    colorRetCode="\033[1;32m$retCode\033[0m"
  else
    colorRetCode="\033[1;31m$retCode\033[0m"
  fi
  description=""
  case $retCode in
    124)
      description="(timed out)"
      ;;
    139)
      description="(seg fault)"
      ;;
  esac
  echo -e "${prefix}     returned code $colorRetCode $description"
}

#------ Beginning --------------------------------------------------------------#

if test $# -lt 1 ; then
  usage
  exit 1
fi

# Defaults
#
timeout=600 # 10 minutes
executeBin="n"
args=""

# Parsing arguments
#
inputBC="$1"
for arg in "$@"; do
  case ${arg} in
    --args=*)
      args="${arg#*=}"
      executeBin="y"
      shift
      ;;
    --timeout=*)
      timeout="${arg#*=}"
      executeBin="y"
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    -*|--*)
      echo "ERROR: Unknown option $arg"
      usage
      exit 1
      ;;
    *)
      ;;
  esac
done

prefix="Selector:"

if [ "$executeBin" == "y" ]; then
  echo "${prefix} The executable will run"
  echo "${prefix}   Arguments: $args"
  echo "${prefix}   Timeout: $timeout seconds"
else
  echo "${prefix} The executable will not run"
fi

loopsInfo=`noelle-parallelizer-plan-info $inputBC 2>&1 | grep "PlanInfo"`
numLoops=$(echo "$loopsInfo" | grep "parallel plan" | egrep -o "[0-9]+")
digitCount=`echo -n "$numLoops" | wc -c`
outputPrefix="parallelized.loop"
echo "$loopsInfo"

for ((i=0; i<numLoops; i++)); do
  echo -e "${prefix} \033[1;37mloop index ${i}\033[0m"
  echo "${prefix}   running noelle-parallelizer-loop"

  i_pad=`printf "%0${digitCount}i" $i`
  outputName="${outputPrefix}${i_pad}"

  # Creating the parallelized bitcode.
  # Only loop number $i will be parallelized.
  #
  noelle-parallelizer-loop $inputBC \
    -o ${outputName}.bc \
    -noelle-loops-white-list=$i \
    -noelle-parallelizer-force \
    -alloc-aa-verbose=1 \
    > ${outputName}.log 2>&1

  showReturnCode $prefix $?

  # Creating the executable
  #
  echo "${prefix}   running clang++"
  clang++ ${outputName}.bc \
    Parallelizer_utils.bc \
    -o ${outputName} \
    -pthreads

  showReturnCode $prefix $?

  # Conditionally run the executable
  #
  if [ "$executeBin" == "y" ]; then
    echo "${prefix}   running binary ${outputName}"
    timeout ${timeout}s ./${outputName} "$args" \
      > /dev/null

    showReturnCode $prefix $?
  fi
  
done

