#!/bin/bash -e

installDir

if test $# -lt 1 ; then
  echo "USAGE: `basename $0` BITCODE"
fi

inputBC=$1
inputLL=`mktemp`
llvm-dis $inputBC -o $inputLL
parallelLoopsCount=`grep -c noelle.parallelizer.looporder $inputLL`
echo "Info: Parallel loops: $parallelLoopsCount"
