#!/bin/bash -e

# It is not guaranteed that noelle-loopsize receives normalized bitcode
# and, more importantly, bitcode where all loops have an ID.
# So, we call a subset of noelle-norm that adds the loop IDs metadata,
# without changing the actual bitcode (i.e., adding/removing instructions),
# which would be incorrect when noelle-loopsize is called in the context of
# noelle-fixedpoint.

set -x
noelle-meta-loop-embed $@ -o $@
noelle-load -loopsize -disable-output -noelle-min-hot=0 $@

