#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

# Check the inputs
if test $# -lt 1 ; then
  echo "USAGE: `basename $0` IR_FILE [OPTIONS]..."
  echo
  echo "Print information about loops in an embedded parallel plan."
  echo
  echo "IR_FILE                     Input bitcode with an embedded parallel plan."
  echo
  echo "Options:"
  echo "--info-print-all-headers    Print the header of every loop."
  echo "--info-print-headers        Print the headers of some loops."
  exit 1
fi

cmdToExecute="noelle-load -noelle-verbose=0 -load ${installDir}/lib/ParallelizerPlanInfo.so -ParallelizerPlanInfo -disable-output $@" 
echo $cmdToExecute
eval $cmdToExecute 
