#!/bin/bash -e

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

# Delete dead functions until a fixed point is reached
echo "NOELLE: Inliner: Start" ;
cmdToExecute="noelle-fixedpoint $1 $1 \"noelle-parallel-load\" -load ${installDir}/lib/Inliner.so -inliner ${@:2}"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: Inliner: Exit" ;
