#!/bin/bash -e

installDir=$(noelle-config --prefix)

# Delete dead functions until a fixed point is reached
echo "NOELLE: DeadFunctions: Start" ;
cmdToExecute="noelle-fixedpoint $1 $2 \"noelle-load\" -DeadFunctionEliminator ${@:3}"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: DeadFunctions: Exit" ;
