#!/bin/bash

installDir

usage() {
  echo "USAGE: `basename $0` INPUT_BC [OPTIONS]..."
  echo
  echo "Tool for parallelizing one loop at a time and running the binary."
  echo
  echo "INPUT_BC        Input bitcode with parallel plan and API already linked."
  echo "                Generally this file is code_to_parallelize.bc"
  echo
  echo "Options:"
  echo "--timeout       Seconds after which the executable will be interruped"
  echo "                causing a non-zero return code."
  echo "                If not specified the binary will not be run."
  echo "--args          Arguments to the executable."
  echo "--help          Display this message."
}

showReturnCode() {
  prefix=$1
  retCode=$2
  if test $retCode -eq 0 ; then
    colorRetCode="\033[1;32m$retCode\033[0m"
  else
    colorRetCode="\033[1;31m$retCode\033[0m"
  fi
  echo -e "${prefix}     returned code $colorRetCode"
}

#------ Beginning --------------------------------------------------------------#

if test $# -lt 1 ; then
  usage
  exit 1
fi

# Defaults
#
timeout=600 # 10 minutes
executeBin="n"
args=""

# Parsing arguments
#
inputBC="$1"
for arg in "$@"; do
  case ${arg} in
    --only=*)
      only="${arg#*=}"
      shift
      ;;
    --args=*)
      args="${arg#*=}"
      executeBin="y"
      shift
      ;;
    --timeout=*)
      timeout="${arg#*=}"
      executeBin="y"
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    -*|--*)
      echo "ERROR: Unknown option $arg"
      usage
      exit 1
      ;;
    *)
      ;;
  esac
done

prefix="Selector:"

if [ "$executeBin" == "y" ]; then
  echo "${prefix} The executable will run"
  echo "${prefix}   Arguments: $args"
  echo "${prefix}   Timeout: $timeout seconds"
else
  echo "${prefix} The executable will not run"
fi

loopsInfo=`noelle-parallelizer-plan-info $inputBC 2>&1 | grep "PlanInfo"`
numLoops=$(echo "$loopsInfo" | grep "parallel plan" | egrep -o "[0-9]+")
digitCount=`echo -n "$numLoops" | wc -c`
outputPrefix="parallelized.loop"
echo "$loopsInfo"

for ((i=0; i<numLoops; i++)); do
  echo -e "${prefix} \033[1;37mloop index ${i}\033[0m"
  echo "${prefix}   running noelle-parallelizer-loop"

  i_pad=`printf "%0${digitCount}i" $i`

  # Creating the parallelized bitcode.
  # Only loop number $i will be parallelized.
  #
  noelle-parallelizer-loop $inputBC \
    -o ${outputPrefix}${i_pad}.bc \
    -noelle-select-only-loops=$i \
    -noelle-parallelizer-force \
    -alloc-aa-verbose=1 \
    > ${outputPrefix}${i_pad}.log 2>&1

  showReturnCode $prefix $?

  # Creating the executable
  #
  echo "${prefix}   running clang++"
  clang++ ${outputPrefix}${i_pad}.bc \
    Parallelizer_utils.bc \
    -o ${outputPrefix}${i_pad} \
    -pthreads

  showReturnCode $prefix $?

  # Conditionally run the executable
  #
  if [ "$executeBin" == "y" ]; then
    echo "${prefix}   running ${outputPrefix}${i_pad}"
    timeout ${timeout}s ./${outputPrefix}${i_pad} "$args" \
      > /dev/null

    showReturnCode $prefix $?
  fi
  
done

