#!/bin/bash -e

installDir=$(noelle-config --prefix)

# Run the privatizer until a fixed point is reached
echo "NOELLE: Privatizer: Start" ;
cmdToExecute="noelle-fixedpoint $1 $1 \"noelle-load\" -privatizer ${@:2}"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: Privatizer: Exit" ;
