#!/bin/bash -e

installDir

# Delete dead functions until a fixed point is reached
echo "NOELLE: Inliner: Start" ;
cmdToExecute="noelle-fixedpoint $1 $1 \"noelle-parallel-load\" -load ${installDir}/lib/Inliner.so -inliner ${@:2}"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: Inliner: Exit" ;
