#!/bin/bash -e

# delete dead functions until a fixed point is reached
echo "NOELLE: DeadFunctions: Start" ;

set -x
noelle-fixedpoint $1 $2 "noelle-load" -DeadFunctionEliminator ${@:3}
set +x

echo "NOELLE: DeadFunctions: Exit" ;
