#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-load -load ${installDir}/lib/Repl.so -repl $@ -disable-output"
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute