#!/bin/bash

installDir

inputIR=$1
intermediateResult="baseline_with_parallel_plan.bc"
outputIR=$3

# Step 1: Run parallelization planner
cmdToExecute="noelle-parallelization-planner ${inputIR} -o ${intermediateResult} ${@:4}" ;
echo $cmdToExecute ;
eval $cmdToExecute ;

# Step 2: Run loop parallelization on bitcode with parallel plan
cmdToExecute="noelle-parallelizer-loop ${intermediateResult} -o ${outputIR} ${@:4}" ;
echo $cmdToExecute ;
eval $cmdToExecute ;
