#!/bin/bash -e

installDir

# Configurations
enablePrivatizer="1" ;
enableEnablers="1" ;
enableDead="1" ;

# Partition the arguments between options and not
options="" ;
notOptions="" ;
for var in "$@" ; do
  if [[ $var == -* ]] ; then

    # Handle custom options
    if [[ $var == "-noelle-disable-privatizer" ]] ; then
      enablePrivatizer="0" ;
      continue ;
    fi
    if [[ $var == "-noelle-disable-enablers" ]] ; then
      enableEnablers="0" ;
      continue ;
    fi
    if [[ $var == "-noelle-disable-dead" ]] ; then
      enableDead="0" ;
      continue ;
    fi
    if [[ $var == -noelle-parallelizer-* ]] ; then

      # Skip all parallelizer-specific options
      continue ;
    fi

    # General options
    options="$options $var" ;

  else 
    notOptions="$notOptions $var" ;
  fi
done

# Strip debugging symbols 
cmdToExecute="opt --strip-debug --strip-debug-declare $notOptions -o $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Delete dead functions
if test "$enableDead" == "1" ; then
  cmdToExecute="noelle-deadcode $notOptions $notOptions"
  echo $cmdToExecute ;
  eval $cmdToExecute ;
fi

# Normalize the code
cmdToExecute="noelle-simplification $notOptions -o $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Make file accesses more amenable for parallelization
cmdToExecute="noelle-io $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Inline functions
cmdToExecute="noelle-inline $notOptions \"-noelle-inliner-verbose=1 $options\""
echo $cmdToExecute ;
eval $cmdToExecute ;

# Normalize the code
cmdToExecute="noelle-simplification $notOptions -o $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Delete dead functions
if test "$enableDead" == "1" ; then
  cmdToExecute="noelle-deadcode $notOptions $notOptions"
  echo $cmdToExecute ;
  eval $cmdToExecute ;
fi

# Normalize the code
cmdToExecute="noelle-simplification $notOptions -o $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Run the privatizer
if test "$enablePrivatizer" == "1" ; then
  cmdToExecute="noelle-privatizer $notOptions $options"
  echo $cmdToExecute ;
  eval $cmdToExecute ;
fi

# Run the enablers
if test "$enableEnablers" == "1" ; then
  cmdToExecute="noelle-enable $notOptions $notOptions $options"
  echo $cmdToExecute ;
  eval $cmdToExecute ;
fi

# Normalize the code
cmdToExecute="noelle-simplification $notOptions -o $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Clean up the metadata that is no longer valid
cmdToExecute="noelle-meta-clean $notOptions $notOptions"
echo $cmdToExecute ;
eval $cmdToExecute ;
