#!/bin/bash -e

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

# Code transformations
ENABLERS="-load ${installDir}/lib/LoopDistribution.so \
  -load ${installDir}/lib/LoopUnroll.so \
  -load ${installDir}/lib/LoopWhilify.so \
  -load ${installDir}/lib/LoopInvariantCodeMotion.so \
  -load ${installDir}/lib/SCEVSimplification.so \
"

# Run the enablers until a fixed point is reached
echo "NOELLE: Enablers: Start" ;
cmdToExecute="noelle-fixedpoint $1 $2 \"noelle-parallel-load\" ${ENABLERS} -load ${installDir}/lib/Enablers.so -enablers ${@:3}"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "NOELLE: Enablers: Exit" ;
