all:

clean:
	cd simple ; ./scripts/clean.sh
	cd pdg ; ./scripts/clean.sh
	cd callgraph ; ./scripts/clean.sh
	cd loops ; ./scripts/clean.sh
	cd profile ; ./scripts/clean.sh
	cd dfa ; ./scripts/clean.sh
	cd dfa2 ; ./scripts/clean.sh
	cd dfa3 ; ./scripts/clean.sh

.PHONY: clean
