#!/bin/bash -e

installDir

# Normalize the code
cmdToExecute="noelle-norm $@ -o $@"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Inline functions
cmdToExecute="noelle-inline -inliner-verbose=1 $@"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Normalize the code
cmdToExecute="noelle-norm $@ -o $@"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Run the enablers
cmdToExecute="noelle-enable $@ $@"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Normalize the code
cmdToExecute="noelle-norm $@ -o $@"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Add metadata to all loops of the program
cmdToExecute="noelle-meta-loop-embed $@ -o $@"
echo $cmdToExecute ;
eval $cmdToExecute ;
