#!/bin/bash

installDir

OPT="opt" ;

########### Analyses
ANALYSES="-scalar-evolution -loops -loop-simplify -lcssa -domtree"


########### Analyses and transformation supports
OPTPASSES="-load ${installDir}/lib/Architecture.so -load ${installDir}/lib/DataFlow.so -load ${installDir}/lib/HotProfiler.so -load ${installDir}/lib/Loops.so"


# Set the command to execute
cmdToExecute="${OPT} ${OPTPASSES} ${ANALYSES} ${@}"

# Execute the command
eval $cmdToExecute 
