#!/bin/bash

installDir

# Clean PDG Metadata
cmdToExecute="noelle-meta-clean $1 -o $1"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Embed PDG Metadata
cmdToExecute="noelle-load -PDGAnalysis -noelle-pdg-verbose=3 $@"
echo $cmdToExecute ;
eval $cmdToExecute ;
