#!/bin/bash

installDir

OPT="opt" ;

########### Analyses
AA="-globals-aa -cfl-steens-aa -tbaa -scev-aa -cfl-anders-aa"
ANALYSES="${AA} -scalar-evolution -loops -loop-simplify -lcssa -domtree"

WPAPASS="-load ${installDir}/lib/libSvf.so -load ${installDir}/lib/libCudd.so -veto -nander -hander -sander -sfrander -wander -ander -fspta -lander -hlander -stat=false"
PDGPASS="-load ${installDir}/lib/AllocAA.so -load ${installDir}/lib/TalkDown.so -load ${installDir}/lib/PDGAnalysis.so"


########### Transformations
ENABLERS="-load ${installDir}/lib/LoopDistribution.so"
PARALLELIZATION_TECHNIQUES="-load ${installDir}/lib/DSWP.so -load ${installDir}/lib/DOALL.so -load ${installDir}/lib/HELIX.so"

OPTPASSES="${WPAPASS} ${PDGPASS} -load ${installDir}/lib/Architecture.so -load ${installDir}/lib/DataFlow.so -load ${installDir}/lib/HotProfiler.so -load ${installDir}/lib/Loops.so -load ${installDir}/lib/Parallelization.so -load ${installDir}/lib/Heuristics.so -load ${installDir}/lib/ParallelizationTechnique.so ${ENABLERS} ${PARALLELIZATION_TECHNIQUES} -load ${installDir}/lib/Parallelizer.so"

# Set the command to execute
cmdToExecute="${OPT} ${OPTPASSES} ${ANALYSES} ${@}"

# Execute the command
eval $cmdToExecute 
