#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-load -parallelization -pgo-test-profile-file=$1 -block-freq -pgo-instr-use -HotProfiler -heuristics -parallelizer ${@:2}"
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
