#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-basic -load ${installDir}/lib/LoopMetadata.so -LoopMetadata ${@}"
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
