#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-load -load ${installDir}/lib/LoopStats.so -LoopStats $@ -disable-output" 
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
