#!/bin/bash

installDir

OPT="opt" ;

########### Analyses
AA_BASE="-basicaa"



########### Transformations
TRANSFORMATIONS_BEFORE_PARALLELIZATION="${AA_BASE} -mem2reg -simplifycfg -instcombine -tailcallelim -loop-simplify -lcssa -loop-unswitch -instcombine -loop-simplify -lcssa -indvars -loop-deletion -instcombine -indvars"


cmdToExecute="${OPT} ${TRANSFORMATIONS_BEFORE_PARALLELIZATION} $@"
echo $cmdToExecute ;

eval $cmdToExecute 
