#!/bin/bash

echo "NOELLE-PARALLEL-AUTOTUNER: Start" ;

cd "`pwd`" ;

# Fetch the number of dimensions
totalDims=`awk '
  {
    tot = 0;
    for (i=1; i <= NF; i++){
      if ($i > 1) {
        tot++ ;
      }
    }
    print tot ;
  }' $RANGE_FILE` ;
echo "AUTOTUNER:  There are $totalDims dimensions in the design space" ;

# Compute the total number of points in the design space
totalNum=`awk '
  {
    tot = 1;
    for (i=1; i <= NF; i++){
      tot *= $i ;
    }
    print tot
  }' $RANGE_FILE` ;
echo "AUTOTUNER:  There are $totalNum points in the design space" ;

# Define the initial configuration
totalDimsMinus1=`echo "$totalDims - 1" | bc` ;
totalDimsMinus2=`echo "$totalDims - 2" | bc` ;
echo -n "{" > ${REPO_PATH}/tmp.json ;
for i in `seq 0 $totalDimsMinus2` ; do
  echo -n "\"${i}\": 0, " >> ${REPO_PATH}/tmp.json ;
done
echo -n "\"${totalDimsMinus1}\": 0 " >> ${REPO_PATH}/tmp.json ;
echo -n "}" >> ${REPO_PATH}/tmp.json ;

# Invoke the autotuner
#python autotuneProgram.py --no-dups --stop-after=$1 --parallelism=1 --test-limit="$totalNum" --seed-configuration="${REPO_PATH}/tmp.json"
python autotuneProgram.py --no-dups --stop-after=$1 --parallelism=1
exitCode=$? ;

echo "NOELLE-PARALLEL-AUTOTUNER: Exit" ;
exit $exitCode ;
