#!/bin/bash -ex

# process the raw data
outputFile=`mktemp`
llvm-profdata merge $1 -output=$outputFile

# run hotprofiler
opt -pgo-test-profile-file=${outputFile} -block-freq -pgo-instr-use ${@:2}

# clean
rm $outputFile
