#!/bin/bash -e

installDir=$(noelle-config --prefix)

if test $# -lt 2 ; then
  echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE" ;
  exit 1;
fi

# Remove the PDG from the bitcode
cmdToExecute="noelle-load -MetadataCleaner -clean-loop-metadata=true $@" 
echo $cmdToExecute ;
eval $cmdToExecute 
