#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

OPT="opt" ;

########### LLVM analyses
AA_BASE="-basicaa"


###########     SVF
if test -f "${installDir}/lib/libSvf.so" ; then
  WPAPASS="-load ${installDir}/lib/libSvf.so -load ${installDir}/lib/libCudd.so -stat=false"
  WPAPASSINV="-break-constgeps"
else
  WPAPASS="" ;
  WPAPASSINV=""
fi


########### Transformations
TRANSFORMATIONS_BEFORE_PARALLELIZATION="${AA_BASE} ${WPAPASS} -mem2reg -tbaa -early-cse-memssa -licm -simplifycfg -simplifycfg-sink-common=false -instcombine -tailcallelim -loop-simplify -lcssa -licm -loop-unswitch -globalopt -instcombine -ipsccp -dce -gvn -dse -adce -loop-simplify -lcssa -indvars -loop-deletion -instcombine -indvars ${WPAPASSINV} -lowerswitch -sroa -mergereturn --break-crit-edges -loop-simplify -lcssa --functionattrs --rpo-functionattrs"


# Simplify the code
cmdToExecute="${OPT} ${TRANSFORMATIONS_BEFORE_PARALLELIZATION} $@"
echo $cmdToExecute ;
eval $cmdToExecute 
