#!/bin/bash

installDir

# Code transformations
ENABLERS="-load ${installDir}/lib/LoopDistribution.so \
  -load ${installDir}/lib/LoopUnroll.so \
  -load ${installDir}/lib/LoopWhilify.so \
  -load ${installDir}/lib/LoopInvariantCodeMotion.so \
  -load ${installDir}/lib/SCEVSimplification.so \
"

echo "NOELLE: Enablers: Start" ;

# Set the command to execute the enablers
cmdToExecute="noelle-fixedpoint $1 $2 ${ENABLERS} -load ${installDir}/lib/Enablers.so -enablers ${@:3}"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Exit
echo "NOELLE: Enablers: Exit" ;
