#!/bin/bash -e

installDir=$(noelle-config --prefix)

# Remove the PDG from the bitcode
cmdToExecute="noelle-load -MetadataCleaner -clean-pdg-scc-metadata $@"
echo $cmdToExecute ;
eval $cmdToExecute 
