#!/bin/bash

installDir

OPT="opt" ;

########### LLVM analyses
AA_BASE="-basic-aa"


###########     SVF
if test -f "${installDir}/lib/libSvf.so" ; then
  WPAPASS="-load ${installDir}/lib/libSvf.so -load ${installDir}/lib/libCudd.so -stat=false"
  WPAPASSINV="-break-constgeps"
else
  WPAPASS="" ;
  WPAPASSINV=""
fi


########### Transformations
TRANSFORMATIONS_BEFORE_PARALLELIZATION="${AA_BASE} ${WPAPASS} -mem2reg -tbaa -early-cse-memssa -licm -simplifycfg -simplifycfg-sink-common=false -instcombine -tailcallelim -loop-simplify -lcssa -licm -globalopt -instcombine -ipsccp -dce -gvn -dse -adce -loop-simplify -lcssa -indvars -loop-deletion -instcombine -indvars ${WPAPASSINV} -lowerswitch -sroa -mergereturn --break-crit-edges -loop-simplify -lcssa --function-attrs --rpo-function-attrs"


# Simplify the code
cmdToExecute="${OPT} ${TRANSFORMATIONS_BEFORE_PARALLELIZATION} $@"
echo $cmdToExecute ;
eval $cmdToExecute 
