#!/bin/bash

if test $# -lt 2 ; then
  echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE" ;
  exit 1;
fi

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

# Remove the PDG from the bitcode
cmdToExecute="noelle-load -MetadataCleaner -clean-prof-metadata=true $@" 
echo $cmdToExecute ;
eval $cmdToExecute 
