#!/bin/bash -e

installDir=$(noelle-config --prefix)

# Set the command to execute
cmdToExecute="noelle-load -PDGGenerator -noelle-pdg-verbose=3 -noelle-pdg-dump -disable-output $@" 
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
