#!/bin/bash -e

installDir=$(noelle-config --prefix)

# Embed PDG Metadata
cmdToExecute="noelle-load -PDGGenerator -noelle-pdg-verbose=3 -noelle-pdg-scc-embed $@"
echo $cmdToExecute ;
eval $cmdToExecute ;
