#!/bin/bash -e

installDir=$(noelle-config --prefix)

if test $# -lt 2 ; then
  echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE" ;
  exit 1;
fi

# Set the command to execute
cmdToExecute="noelle-load --strip-named-metadata -MetadataCleaner -clean-loop-metadata -clean-prof-metadata -clean-pdg-metadata -clean-pdg-scc-metadata $@" 
echo $cmdToExecute ;
eval $cmdToExecute 
