#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

# Process the raw data
outputFile=`mktemp` ;
llvm-profdata merge $1 -output=$outputFile ;

# Run HotProfiler
cmdToExecute="opt -pgo-test-profile-file=${outputFile} -block-freq -pgo-instr-use ${@:2}"
echo $cmdToExecute ;
eval $cmdToExecute ;

# Clean
rm $outputFile ;
