#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-parallel-load -load ${installDir}/lib/Parallelizer.so -parallelizer ${@}"
echo $cmdToExecute ;

# Execute
eval $cmdToExecute ;
