#!/bin/bash -e

installDir=$(noelle-config --prefix)

OPT="opt"

# Check the inputs
if test $# -lt 1 ; then
  echo "USAGE: `basename $0` OPT-OPTIONS"
  exit 1;
fi

###########     LLVM alias analyses
AA="-disable-basicaa -globals-aa -cfl-steens-aa -tbaa -scev-aa -cfl-anders-aa --objc-arc-aa"
EXTRA_AA=""

###########     SCAF
if test -f "${installDir}/lib/libSCAFUtilities.so" ; then
  SCAFPASS="-load ${installDir}/lib/libSCAFUtilities.so -load ${installDir}/lib/libMemoryAnalysisModules.so"
  LOOP_AA=`loopaa`
  EXTRA_AA="${EXTRA_AA} -noelle-scaf"
else
  SCAFPASS=""
  LOOP_AA=" "
fi

###########     SVF
if test -f "${installDir}/lib/libSvf.so" ; then
  WPAPASS="-load ${installDir}/lib/libSvf.so -load ${installDir}/lib/libCudd.so -stat=false"
  EXTRA_AA="${EXTRA_AA} -noelle-svf"
else
  WPAPASS=""
fi

ANALYSES="${AA} ${LOOP_AA} -scalar-evolution -loops -domtree -postdomtree ${EXTRA_AA}"
OPTPASSES="${WPAPASS} ${SCAFPASS} -load ${installDir}/lib/NoelleCore.so -load ${installDir}/lib/NoelleTools.so ${PDGPASS}"

# Set the command to execute
cmdToExecute="${OPT} ${OPTPASSES} ${ANALYSES} ${@}"

# Execute the command
echo $cmdToExecute
eval $cmdToExecute
